#config file hosts.yml
---
datacenter:
  children:
    router:
      hosts:
        R1:
          ansible_host: 10.215.27.34
        R2:
          ansible_host: 10.215.27.99
  Vars:
  ansible_become_password: vnpro#321
  ansible_user: vnpro
  ansible_password: vnpro@123
  ansible_connection: network_cli
  ansible_become: "yes"
  ansible_become_method: "enable"
  ansible_network_os: ios


#configure router.yml
---
- name: configure Router1
  hosts: R1

  tasks:
    - name: Set ip
      ios_config:
        line:
        - no shutdown
        - ip address 192.168.{{ item.ip }} 255.255.255.0
        parents: "{{ item.int }}"
      loop:
      - {ip: 1.1, int: int Ethernet0/1}
      - {ip: 12.1, int: int Ethernet0/2}

========================
#static route
- name: configure static route
  ios_static_route:
    prefix: 192.168.2.0
    mask: 255.255.255.0
    next_hop: 192.168.12.2